# Generated by Django 3.0.7 on 2020-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartHouse',
            fields=[
                ('HouseID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='House_ID')),
                ('HouseName', models.CharField(max_length=200, verbose_name='House_name')),
                ('Country', models.CharField(max_length=200, verbose_name='Country')),
                ('Adress', models.CharField(max_length=200, verbose_name='Adress')),
                ('TimeCreated', models.DateTimeField(verbose_name='Date_created')),
            ],
        ),
    ]
